name: Merge PRs with Staging Label

on:
  pull_request:
    types: [labeled, synchronize, reopened, closed]

permissions:
  pull-requests: write
  contents: write
  issues: write
  checks: write
  statuses: write

jobs:
  merge-and-save:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Node.js and dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install axios

      - name: Create and Checkout merge-temp branch
        run: |
          git fetch origin
          git checkout -b merge-temp || git checkout merge-temp

      - name: Check if PR has using:staging label
        id: check-label
        run: |
          LABELS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/labels" | jq -r '.[].name')

          echo "Labels on PR: $LABELS"

          if [[ "$LABELS" == *"using:staging"* ]]; then
            echo "PR has using:staging label"
            echo "::set-output name=has_label::true"
          else
            echo "PR does not have using:staging label"
            echo "::set-output name=has_label::false"
          fi

      - name: Merge PRs with using:staging label
        if: steps.check-label.outputs.has_label == 'true'
        run: |
          node -e "
            const axios = require('axios');
            const fs = require('fs');
            const { execSync } = require('child_process');

            const GITHUB_REPOSITORY = process.env.GITHUB_REPOSITORY;
            const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
            const PR_NUMBER = process.env.PR_NUMBER;
            const CURRENT_BRANCH = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH)).pull_request.head.ref;

            const headers = {
              'Authorization': \`token \${GITHUB_TOKEN}\`,
              'Accept': 'application/vnd.github.v3+json'
            };

            async function getPRs() {
              const response = await axios.get(\`https://api.github.com/repos/\${GITHUB_REPOSITORY}/pulls\`, { headers });
              return response.data.filter(pr => pr.labels.some(label => label.name === 'using:staging') && pr.number !== PR_NUMBER);
            }

            async function getCheckRuns(commitSha) {
              const response = await axios.get(\`https://api.github.com/repos/\${GITHUB_REPOSITORY}/commits/\${commitSha}/check-runs\`, { headers });
              return response.data.check_runs;
            }

            async function main() {
              try {
                execSync('git fetch origin');

                const prs = await getPRs();
                console.log('Fetched PRs with using:staging label:', prs);

                const successfulPRs = [];

                for (const pr of prs) {
                  const checkRuns = await getCheckRuns(pr.head.sha);
                  const failedChecks = checkRuns.filter(check => check.conclusion !== 'success');

                  if (failedChecks.length > 0) {
                    const failedCheckNames = failedChecks.map(check => \`\${check.name}: \${check.conclusion}\`).join('\\n');
                    console.log(\`PR #\${pr.number} has failed checks:\\n\${failedCheckNames}\`);

                    await axios.post(\`https://api.github.com/repos/\${GITHUB_REPOSITORY}/issues/\${pr.number}/comments\`, {
                      body: \`The following status checks failed for PR #\${pr.number}:\\n\${failedCheckNames}\`
                    }, { headers });

                    continue;
                  }

                  successfulPRs.push(pr.number);
                }

                console.log('Merging successful PRs with current PR:', successfulPRs);

                for (const prNumber of successfulPRs) {
                  console.log(\`Merging PR #\${prNumber}\`);
                  execSync(\`git fetch origin pull/\${prNumber}/head:pr-\${prNumber}\`);
                  try {
                    execSync(\`git merge pr-\${prNumber} --no-commit --allow-unrelated-histories\`);
                    execSync('git add .');
                    execSync('git commit -m \"Merged PRs with current PR\"');
                  } catch (error) {
                    console.error(\`Conflict detected in PR #\${prNumber}\`);
                    await axios.post(\`https://api.github.com/repos/\${GITHUB_REPOSITORY}/issues/\${prNumber}/comments\`, {
                      body: \`Conflict detected during merge with PR #\${prNumber}. Please resolve manually.\`
                    }, { headers });

                    execSync('git merge --abort');
                    process.exit(1);
                  }
                }

                // Commit and push changes
                execSync('git push origin merge-temp');

                console.log('Merge concluded successfully');
              } catch (error) {
                console.error('Error during merge process:', error);
                process.exit(1);
              }
            }

            main();
          "
